import { MenuItem, Branch } from './types';

export const branches: Branch[] = [
    {
        id: 'br1',
        name: 'Sangam Hotels - Anna Nagar',
        address: '123 Main Street, Anna Nagar, Hyderabad - 600040',
        phone: '+91 98765 43210',
        image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=1200',
        features: ['Rooftop Dining', 'Valet Parking', 'Live Music', 'Private Suites', 'Award-Winning Decor'],
        coordinates: { lat: 17.4401, lng: 78.3489 },
        openHours: '11:00 AM - 11:00 PM'
    },
    {
        id: 'br2',
        name: 'Sangam Hotels - T Nagar',
        address: '456 Pondy Bazaar, T Nagar, Hyderabad - 600017',
        phone: '+91 98765 43211',
        image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&q=80&w=1200',
        features: ['Luxury Banquet Hall', 'Chef Special Table', 'Kid Zone', 'Valet Parking', 'Corporate Dining'],
        coordinates: { lat: 17.4448, lng: 78.3498 },
        openHours: '10:00 AM - 11:30 PM'
    },
    {
        id: 'br3',
        name: 'Sangam Hotels - Velachery',
        address: '789 Velachery Main Road, Hyderabad - 600042',
        phone: '+91 98765 43212',
        image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&q=80&w=1200',
        features: ['Garden Seating', 'Pet Friendly', 'Organic Kitchen', 'Dedicated Takeaway', 'Weekend Brunch'],
        coordinates: { lat: 17.4360, lng: 78.3410 },
        openHours: '11:00 AM - 12:00 AM'
    },
    {
        id: 'br4',
        name: 'Sangam Hotels - OMR',
        address: '321 Old Mahabalipuram Road, Hyderabad - 600096',
        phone: '+91 98765 43213',
        image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&q=80&w=1200',
        features: ['Express Delivery', 'Work-Friendly Pods', '24/7 Buffet', 'EV Charging', 'IT Professional Hub'],
        coordinates: { lat: 17.4265, lng: 78.3383 },
        openHours: '10:00 AM - 11:00 PM'
    },
    {
        id: 'br5',
        name: 'Sangam Hotels - Adyar',
        address: '654 Lattice Bridge Road, Adyar, Hyderabad - 600020',
        phone: '+91 98765 43214',
        image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&q=80&w=1200',
        features: ['Heritage Ambiance', 'Traditional Pottery', 'Beach View', 'Cultural Shows', 'Luxury Fine Dining'],
        coordinates: { lat: 17.4167, lng: 78.3282 },
        openHours: '11:30 AM - 11:00 PM'
    }
];

export const menuItems: MenuItem[] = [
    {
        id: 'm1',
        name: 'Butter Chicken',
        description: 'Tender tandoori chicken simmered in a velvety tomato and butter gravy with aromatic spices.',
        price: 495,
        discount: 10,
        category: 'Main Course',
        foodType: 'non-veg',
        image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&q=80&w=800',
        branch: ['br1', 'br2', 'br3', 'br4', 'br5'],
        isSpecial: true,
        available: true,
        rating: 4.9
    },
    {
        id: 'm2',
        name: 'Paneer Tikka Masala',
        description: 'Succulent cubes of grilled cottage cheese tossed in a robust and spicy tomato-based masala.',
        price: 385,
        discount: 5,
        category: 'Main Course',
        foodType: 'veg',
        image: 'https://images.unsplash.com/photo-1631451095765-2c9111619e41?auto=format&fit=crop&q=80&w=800',
        branch: ['br1', 'br2', 'br3', 'br4', 'br5'],
        isSpecial: true,
        available: true,
        rating: 4.8
    },
    {
        id: 'm3',
        name: 'Chicken Dum Biryani',
        description: 'Authentic Hyderabadi style slow-cooked rice with marinated chicken, saffron, and traditional spices.',
        price: 450,
        discount: 15,
        category: 'Biryani',
        foodType: 'non-veg',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21bc4a6f8?auto=format&fit=crop&q=80&w=800',
        branch: ['br1', 'br2', 'br3', 'br4', 'br5'],
        isSpecial: true,
        available: true,
        rating: 4.9
    },
    {
        id: 'm4',
        name: 'Vegetable Dum Biryani',
        description: 'Fragrant Basmati rice layered with seasonal vegetables and exotic spices, slow-cooked to perfection.',
        price: 360,
        discount: 10,
        category: 'Biryani',
        foodType: 'veg',
        image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&q=80&w=800',
        branch: ['br1', 'br2', 'br3', 'br4', 'br5'],
        isSpecial: false,
        available: true,
        rating: 4.7
    },
    {
        id: 'm5',
        name: 'Traditional Tandoori Chicken',
        description: 'Classic clay-oven roasted chicken marinated in yogurt and a special house blend of spices.',
        price: 550,
        discount: 0,
        category: 'Tandoor',
        foodType: 'non-veg',
        image: 'https://images.unsplash.com/photo-1626074353765-517a681e406e?auto=format&fit=crop&q=80&w=800',
        branch: ['br1', 'br3', 'br4', 'br5'],
        isSpecial: true,
        available: true,
        rating: 4.8
    },
    {
        id: 'm6',
        name: 'Dal Sangam Special',
        description: 'Our signature black lentils slow-cooked for 24 hours with butter and fresh cream.',
        price: 295,
        discount: 0,
        category: 'Main Course',
        foodType: 'veg',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800',
        branch: ['br1', 'br2', 'br3', 'br4', 'br5'],
        isSpecial: false,
        available: true,
        rating: 4.9
    },
    {
        id: 'm7',
        name: 'Tangy Fish Curry',
        description: 'Fresh catch of the day cooked in a typical South Indian style tamarind and onion-based gravy.',
        price: 520,
        discount: 20,
        category: 'Seafood',
        foodType: 'non-veg',
        image: 'https://images.unsplash.com/photo-1626777558305-b84e03f1eb81?auto=format&fit=crop&q=80&w=800',
        branch: ['br2', 'br3', 'br5'],
        isSpecial: true,
        available: true,
        rating: 4.7
    },
    {
        id: 'm8',
        name: 'Garlic Prawn Masala',
        description: 'Juicy tiger prawns stir-fried with golden garlic and spicy masala gravy.',
        price: 640,
        discount: 10,
        category: 'Seafood',
        foodType: 'non-veg',
        image: 'https://images.unsplash.com/photo-1551529834-523abc4f99db?auto=format&fit=crop&q=80&w=800',
        branch: ['br1', 'br3', 'br5'],
        isSpecial: true,
        available: true,
        rating: 4.9
    },
    {
        id: 'm9',
        name: 'Assorted Bread Basket',
        description: 'A selection of Garlic Naan, Butter Naan, and Laccha Paratha.',
        price: 220,
        discount: 0,
        category: 'Breads',
        foodType: 'veg',
        image: 'https://images.unsplash.com/photo-1633945274405-b6c80a203bc3?auto=format&fit=crop&q=80&w=800',
        branch: ['br1', 'br2', 'br3', 'br4', 'br5'],
        isSpecial: false,
        available: true,
        rating: 4.6
    },
    {
        id: 'm10',
        name: 'Royal Gulab Jamun',
        description: 'Warm, syrup-soaked milk dumplings served with a hint of cardamom and silver leaf.',
        price: 180,
        discount: 0,
        category: 'Desserts',
        foodType: 'veg',
        image: 'https://images.unsplash.com/photo-1589113824040-fb974f179c6b?auto=format&fit=crop&q=80&w=800',
        branch: ['br1', 'br2', 'br3', 'br4', 'br5'],
        isSpecial: false,
        available: true,
        rating: 4.8
    },
    {
        id: 'm11',
        name: 'Mutton Rogan Josh',
        description: 'Tender mutton pieces slow-cooked in a rich gravy of Kashmiri chilies and aromatic spices.',
        price: 595,
        discount: 10,
        category: 'Main Course',
        foodType: 'non-veg',
        image: 'https://images.unsplash.com/photo-1545241047-6083a3684587?auto=format&fit=crop&q=80&w=800',
        branch: ['br1', 'br2', 'br4'],
        isSpecial: true,
        available: true,
        rating: 4.9
    },
    {
        id: 'm12',
        name: 'Palak Paneer',
        description: 'Fresh spinach puree combined with soft cottage cheese cubes and tempered with garlic.',
        price: 345,
        discount: 5,
        category: 'Main Course',
        foodType: 'veg',
        image: 'https://images.unsplash.com/photo-1601050638917-3f0460bc4b52?auto=format&fit=crop&q=80&w=800',
        branch: ['br1', 'br2', 'br3', 'br4', 'br5'],
        isSpecial: false,
        available: true,
        rating: 4.7
    },
    {
        id: 'm13',
        name: 'Malai Kofta',
        description: 'Vegetable and paneer dumplings simmered in a creamy, sweet onion and tomato gravy.',
        price: 395,
        discount: 0,
        category: 'Main Course',
        foodType: 'veg',
        image: 'https://images.unsplash.com/photo-1585937421612-71a008356fbe?auto=format&fit=crop&q=80&w=800',
        branch: ['br1', 'br3', 'br5'],
        isSpecial: true,
        available: true,
        rating: 4.8
    },
    {
        id: 'm14',
        name: 'Prawn Tempura',
        description: 'Crispy, deep-fried prawns served with a spicy dipping sauce, perfect for a starter.',
        price: 480,
        discount: 15,
        category: 'Starters',
        foodType: 'non-veg',
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800',
        branch: ['br2', 'br4', 'br5'],
        isSpecial: false,
        available: true,
        rating: 4.6
    },
    {
        id: 'm15',
        name: 'Gobi Manchurian',
        description: 'Indo-Chinese style crispy cauliflower florets tossed in a tangy and spicy soy-based sauce.',
        price: 280,
        discount: 20,
        category: 'Starters',
        foodType: 'veg',
        image: 'https://images.unsplash.com/photo-1512058560374-140fa3d8fc42?auto=format&fit=crop&q=80&w=800',
        branch: ['br1', 'br2', 'br3', 'br4', 'br5'],
        isSpecial: false,
        available: true,
        rating: 4.5
    },
    {
        id: 'm16',
        name: 'Mixed Vegetable Pulao',
        description: 'Lightly spiced Basmati rice cooked with fresh seasonal vegetables and whole spices.',
        price: 310,
        discount: 0,
        category: 'Biryani',
        foodType: 'veg',
        image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&q=80&w=800',
        branch: ['br1', 'br2', 'br3', 'br4', 'br5'],
        isSpecial: false,
        available: true,
        rating: 4.6
    },
    {
        id: 'm17',
        name: 'Stuffed Naan Basket',
        description: 'A selection of Paneer Stuffed Naan, Aloo Kulcha, and Peshawari Naan.',
        price: 280,
        discount: 5,
        category: 'Breads',
        foodType: 'veg',
        image: 'https://images.unsplash.com/photo-1626074353765-517a681e406e?auto=format&fit=crop&q=80&w=800',
        branch: ['br1', 'br2', 'br3', 'br4', 'br5'],
        isSpecial: false,
        available: true,
        rating: 4.7
    },
    {
        id: 'm18',
        name: 'Kesari Rasmalai',
        description: 'Soft cottage cheese patties soaked in saffron-infused milk and garnished with pistachios.',
        price: 220,
        discount: 0,
        category: 'Desserts',
        foodType: 'veg',
        image: 'https://images.unsplash.com/photo-1589113824040-fb974f179c6b?auto=format&fit=crop&q=80&w=800',
        branch: ['br1', 'br2', 'br3', 'br4', 'br5'],
        isSpecial: true,
        available: true,
        rating: 4.9
    },
    {
        id: 'm19',
        name: 'Fresh Fruit Cream',
        description: 'Seasonal fresh fruits served in a light, chilled cream reduction with a hint of honey.',
        price: 250,
        discount: 10,
        category: 'Desserts',
        foodType: 'veg',
        image: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800',
        branch: ['br1', 'br3', 'br5'],
        isSpecial: false,
        available: true,
        rating: 4.8
    },
    {
        id: 'm20',
        name: 'Hyderabadi Haleem',
        description: 'A seasonal delicacy made of wheat, barley, meat, and lentils, slow-cooked for hours.',
        price: 420,
        discount: 0,
        category: 'Main Course',
        foodType: 'non-veg',
        image: 'https://images.unsplash.com/photo-1545241047-6083a3684587?auto=format&fit=crop&q=80&w=800',
        branch: ['br1', 'br2', 'br3', 'br4', 'br5'],
        isSpecial: true,
        available: true,
        rating: 5.0
    }
];
